In [ ]:
# !pip install --upgrade pip

In [9]:
import os
import shutil

def clear_python_cache(directory):
    for root, dirs, files in os.walk(directory):
        for dir_name in dirs:
            if dir_name == "__pycache__":
                cache_dir = os.path.join(root, dir_name)
                shutil.rmtree(cache_dir)
                print(f"Gelöscht: {cache_dir}")

#  Wurzelverzeichnis:
project_dir = os.getcwd()  # Aktuelles Verzeichnis
clear_python_cache(project_dir)


In [1]:

import os
current_dir = os.getcwd()
src_path = os.path.abspath(os.path.join(current_dir, '../../../1. Explorative Analysis & Preprocessing/nasiba/'))
os.chdir(src_path) 
src_path

'c:\\Users\\Nasiba\\Documents\\Repos_Clones\\WebScience24\\src\\1. Explorative Analysis & Preprocessing\\nasiba'

In [2]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

from collections import Counter
#nlp = spacy.load("en_core_web_sm")

pd.set_option('display.max_colwidth', None)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from src.preprocessing.cleaning.clean_data_generic_functions import remove_na_from_column
from src.preprocessing.vectorizing.vector_functions import vectorize_bag_of_words, vectorize_tfidf, vectorize_word2vec,  vectorize_fasttext, compare_vectorization_methods
import nltk
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Nasiba\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
filepath_name = os.path.abspath(os.path.join(src_path, 'data/train_cleaned.csv'))
df_cleaned = pd.read_csv(filepath_name, encoding='utf-8')
df_cleaned = remove_na_from_column(df=df_cleaned)

#### 1. Bag of Words (BoW)

In [ ]:
X_train_bow, X_test_bow, y_train, y_test, vectorizer  = vectorize_bag_of_words(df=df_cleaned, text_column="tweet_cleaned",
 
                                                                                           label_column="label")
print(vectorizer.get_feature_names_out())

['aamp' 'aap' 'ab' ... 'zootopia' 'zoro' 'zzz']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


##### 2. Term Frequency-Inverse Document Frequency (TF-IDF)

In [8]:
X_train_tfidf, X_test_tfidf, y_train, y_test, tfidf_vectorizer = vectorize_tfidf(df=df_cleaned, text_column='tweet_cleaned', 
                                                                                 label_column="label")

print("Trainingsdaten (TF-IDF-Matrix):")
print(X_train_tfidf.toarray())
print("Feature-Namen:")
print(tfidf_vectorizer.get_feature_names_out())


Trainingsdaten (TF-IDF-Matrix):
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Feature-Namen:
['aamp' 'aap' 'ab' ... 'zootopia' 'zoro' 'zzz']


##### 3. Word Embeddings Word2Vec

In [16]:

X_train_w2v, X_test_w2v, y_train, y_test, w2v_model = vectorize_word2vec(df=df_cleaned, text_column ="tweet_cleaned", label_column="label")

print("Erste Trainingsvektoren:")
print(X_train_w2v[:5])

c:\Users\Nasiba\Documents\Repos_Clones\WebScience24\src\1. Explorative Analysis & Preprocessing\nasiba\src\preprocessing\vectorizing\vector_functions.py:105: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[text_column] = df[text_column].astype(str)


Erste Trainingsvektoren:
[[ 8.86157334e-03  2.93546597e-01  2.85350674e-02 ... -1.24635624e-01
   1.62490445e-01 -3.61440731e-02]
 [-1.63146095e-03  1.87353872e-01  2.77274716e-02 ... -1.08744206e-01
   1.29523960e-01 -1.90963989e-02]
 [ 1.73104461e-04  2.51385506e-01  8.00646017e-02 ... -1.70219562e-01
   1.58880664e-01 -4.80226235e-02]
 [ 4.75607536e-03  2.18909404e-01  2.92647363e-02 ... -1.12264831e-01
   1.30614392e-01 -2.67828682e-02]
 [-3.23979477e-02  2.21074512e-01  6.07593423e-02 ... -2.51384515e-01
   1.29672541e-01 -3.35288490e-02]]


#### 4. FastText

In [6]:

X_train_ft, X_test_ft, y_train, y_test, ft_model = vectorize_fasttext(
    df=df_cleaned,
    text_column="tweet_cleaned",
    label_column="label",
    vector_size=100,
    window=3,
    min_count=1
)

print("Erste FastText-Vektoren (Trainingsdaten):")
print(X_train_ft[:5])


Erste FastText-Vektoren (Trainingsdaten):
[[-0.29386375 -0.18855044 -0.28949956  0.1476144  -0.01624956  0.13286856
  -0.2226717   0.42894903  0.20227926 -0.34489603  0.14063459 -0.17879955
  -0.02656796  0.35571882  0.14739158 -0.18100273 -0.38855459 -0.38690186
   0.03949845 -0.1420191  -0.38428877  0.12217931 -0.43021867 -0.27014789
  -0.1585444  -0.19736542 -0.1047727  -0.11022075  0.39326515  0.0440884
   0.00890011 -0.11697213  0.26496852  0.09481627 -0.24331411  0.0848361
  -0.30035191  0.16245278 -0.38106031  0.10987324  0.03810994 -0.11336832
  -0.36291646 -0.35525489 -0.30596789 -0.63242    -0.13390998 -0.35441031
  -0.12001625  0.02514511  0.18910217  0.00634514  0.21914639 -0.05554438
  -0.13937775 -0.30562437 -0.07341961 -0.06837617 -0.10356644 -0.14365796
   0.35412748 -0.25115391 -0.28434361  0.4578321   0.03951711  0.10478977
  -0.09506598 -0.16083588 -0.14083032  0.36286939  0.15732638  0.3946838
  -0.32672708 -0.34217629  0.59179797 -0.22814074  0.11298252 -0.28843242

### Vergleiche 4 Methoden

In [ ]:

results = compare_vectorization_methods(df=df_cleaned, text_column="tweet_cleaned", label_column="label")


results.plot(x="Method", y=["Accuracy", "Precision", "Recall", "F1 Score"], kind="bar", figsize=(10, 6))
plt.title("Vergleich der Vektorisierungsmethoden")
plt.ylabel("Score")
plt.xlabel("Vektorisierungsmethode")
plt.legend(loc="best")
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()


Vektorisierung: Bag of Words
Vektorisierung: TF-IDF


ValueError: np.nan is an invalid document, expected byte or unicode string.