In [5]:
%run vf.py

In [6]:
X_train_bow, X_test_bow, y_train_bow, y_test_bow = vectorize_bow()
X_train_tfidf, X_test_tfidf, y_train_tfidf, y_test_tfidf = vectorize_tfidf()
X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = vectorize_w2v()
X_train_ft, X_test_ft, y_train_ft, y_test_ft = vectorize_ft()

In [14]:
print(X_train_bow.shape)
print(X_test_bow.shape)
print(y_train_bow.shape)
print(y_test_bow.shape)
print(type(X_train_bow))

(19354, 6293)
(8295, 5672)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [15]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)
print(y_train_tfidf.shape)
print(y_test_tfidf.shape)
print(type(X_train_tfidf))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [16]:
print(X_train_w2v.shape)
print(X_test_w2v.shape)
print(y_train_w2v.shape)
print(y_test_w2v.shape)
print(type(X_train_w2v))

(19354, 100)
(8295, 100)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [17]:
print(X_train_ft.shape)
print(X_test_ft.shape)
print(y_train_ft.shape)
print(y_test_ft.shape)
print(type(X_train_ft))

(19354, 100)
(8295, 100)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [21]:
print(X_train_bow.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
print(X_train_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [23]:
X_train_w2v

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.30046263, -0.15969649, -0.46144587, ..., -0.30066848,
        -0.11430683,  0.47329196],
       [ 0.01616175, -0.23493344, -0.04933871, ...,  0.18135037,
        -0.17035106,  0.37558433],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [24]:
X_train_ft

array([[ 4.17442854e-04,  1.88850863e-04, -5.85716916e-05, ...,
         8.79152707e-04,  7.50738996e-04, -8.48507538e-04],
       [ 2.56881471e-02, -3.40529280e-02,  1.63892293e-02, ...,
         1.74089659e-02, -1.21213126e-02,  8.98468038e-03],
       [ 8.97156055e-03, -5.32196675e-03, -5.75549687e-03, ...,
         2.38700864e-02, -7.16403337e-02,  1.60573581e-02],
       ...,
       [ 3.99740592e-04,  2.30928903e-04, -6.90983768e-04, ...,
        -3.70803489e-04, -7.98589236e-04, -8.02745365e-04],
       [-7.99766095e-04, -1.28270252e-03, -7.59550901e-04, ...,
        -9.03572654e-05,  8.76524127e-04, -2.05668177e-04],
       [ 9.65976153e-04, -3.22034230e-04, -8.02401310e-04, ...,
        -6.23218932e-04, -1.47446824e-04, -1.18978852e-03]])