In [59]:
%run vectorize_functions.py

In [60]:
X_train_bow, X_test_bow, y_train_bow, y_test_bow = vectorize_bow()
X_train_tfidf, X_test_tfidf, y_train_tfidf, y_test_tfidf = vectorize_tfidf()
X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = vectorize_w2v()
X_train_ft, X_test_ft, y_train_ft, y_test_ft = vectorize_ft()

In [61]:
print(X_train_bow.shape)
print(X_test_bow.shape)
print(y_train_bow.shape)
print(y_test_bow.shape)
print(type(X_train_bow))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [62]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)
print(y_train_tfidf.shape)
print(y_test_tfidf.shape)
print(type(X_train_tfidf))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [63]:
print(X_train_w2v.shape)
print(X_test_w2v.shape)
print(y_train_w2v.shape)
print(y_test_w2v.shape)
print(type(X_train_w2v))

(19354, 100)
(8295, 100)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [64]:
print(X_train_ft.shape)
print(X_test_ft.shape)
print(y_train_ft.shape)
print(y_test_ft.shape)
print(type(X_train_ft))

(19354, 100)
(8295, 100)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [65]:
print(X_train_bow.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [66]:
print(X_train_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [67]:
print(X_train_w2v)

[[-0.01147646  0.03351697  0.03052096 ...  0.26658788 -0.41422737
  -0.96575334]
 [ 0.59317126  1.04517235 -0.68315393 ...  0.5322897   0.21007362
  -0.53926928]
 [-0.51177335  0.26493848  0.14858572 ... -0.05901077  0.26358006
  -0.10099881]
 ...
 [ 0.00811557  0.29221034 -0.2694154  ... -0.57397499  0.38051231
   0.11780225]
 [-0.21425795 -0.28901504 -0.42930262 ... -0.1730243  -0.71195021
   0.10442292]
 [-0.1440051   0.46456884 -0.13090007 ... -0.22812251  0.51409511
  -0.45013019]]


In [68]:
print(X_train_ft)

[[-0.08066028 -0.52482803  0.05279757 ... -0.96275002 -0.02987838
  -0.07440034]
 [ 0.26815086  0.62263645 -0.60711602 ...  0.45138734  0.04387279
  -0.02440794]
 [-0.29407283  0.33694046 -0.20489176 ... -0.28441028  0.41935875
   0.5274036 ]
 ...
 [-0.17667818  0.37669694 -0.29564432 ...  0.08197616  0.099627
   0.00971218]
 [-0.63596682 -0.32718288 -0.32473991 ... -0.1229609  -0.63897318
   0.36509097]
 [-0.05478564  0.12374861 -0.45298569 ...  0.17180451  0.56107108
  -0.14564781]]


#### Test BOW

In [69]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

clf_bow = MultinomialNB()
clf_bow.fit(X_train_bow,y_train_bow)
ypred_bow = clf_bow.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test_bow, ypred_bow))

Accuracy:  0.9410488245931284


In [70]:
from sklearn import tree

clf_bow = tree.DecisionTreeClassifier()
clf_bow.fit(X_train_bow,y_train_bow)
ypred_bow = clf_bow.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test_bow, ypred_bow))

Accuracy:  0.9387582881253768


#### Test TFIDF

In [71]:
clf_tfidf = MultinomialNB()
clf_tfidf.fit(X_train_tfidf,y_train_tfidf)
ypred_tfidf = clf_tfidf.predict(X_test_tfidf)
print("Accuracy: ", accuracy_score(y_test_tfidf, ypred_tfidf))

Accuracy:  0.9482820976491863


In [72]:
clf_tfidf = tree.DecisionTreeClassifier()
clf_tfidf.fit(X_train_tfidf,y_train_tfidf)
ypred_tfidf = clf_tfidf.predict(X_test_tfidf)
print("Accuracy: ", accuracy_score(y_test_tfidf, ypred_tfidf))

Accuracy:  0.9409282700421941


#### Test W2V

In [73]:
from sklearn.naive_bayes import GaussianNB

clf_w2v = GaussianNB()
clf_w2v.fit(X_train_w2v,y_train_w2v)
ypred_w2v = clf_w2v.predict(X_test_w2v)
print("Accuracy: ", accuracy_score(y_test_w2v, ypred_w2v))

Accuracy:  0.7005424954792043


In [74]:
from sklearn import tree

clf_w2v = tree.DecisionTreeClassifier().fit(X_train_w2v, y_train_w2v)
clf_w2v.fit(X_train_w2v,y_train_w2v)
ypred_w2v = clf_w2v.predict(X_test_w2v)
print("Accuracy: ", accuracy_score(y_test_w2v, ypred_w2v))

Accuracy:  0.9075346594333936


#### Test FT

In [75]:
clf_ft = GaussianNB()
clf_ft.fit(X_train_ft,y_train_ft)
ypred_ft = clf_ft.predict(X_test_ft)
print("Accuracy: ", accuracy_score(y_test_ft, ypred_ft))

Accuracy:  0.7363471971066908


In [76]:
clf_ft = tree.DecisionTreeClassifier()
clf_ft.fit(X_train_ft,y_train_ft)
ypred_ft = clf_ft.predict(X_test_ft)
print("Accuracy: ", accuracy_score(y_test_ft, ypred_ft))

Accuracy:  0.9033152501506931
