In [1]:
%run vectorize_functions.py

In [2]:
X_train_bow, X_test_bow, y_train_bow, y_test_bow = vectorize_bow()
X_train_tfidf, X_test_tfidf, y_train_tfidf, y_test_tfidf = vectorize_tfidf()
X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = vectorize_w2v()
X_train_ft, X_test_ft, y_train_ft, y_test_ft = vectorize_ft()

In [3]:
print(X_train_bow.shape)
print(X_test_bow.shape)
print(y_train_bow.shape)
print(y_test_bow.shape)
print(type(X_train_bow))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [4]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)
print(y_train_tfidf.shape)
print(y_test_tfidf.shape)
print(type(X_train_tfidf))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [5]:
print(X_train_w2v.shape)
print(X_test_w2v.shape)
print(y_train_w2v.shape)
print(y_test_w2v.shape)
print(type(X_train_w2v))

(19354, 100)
(8295, 100)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [6]:
print(X_train_ft.shape)
print(X_test_ft.shape)
print(y_train_ft.shape)
print(y_test_ft.shape)
print(type(X_train_ft))

(19354, 100)
(8295, 100)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [7]:
print(X_train_bow.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
print(X_train_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
print(X_train_w2v)

[[-0.07814837  0.19778219  0.16375371 ...  0.29295957 -0.42222694
  -0.60330145]
 [ 0.80851864  0.97765596 -0.6431363  ...  0.33107672 -0.2691976
  -0.44218966]
 [-0.42487646  0.44140847  0.19626938 ...  0.05067893  0.06511918
   0.04168098]
 ...
 [ 0.02289515  0.336278   -0.07386641 ... -0.47144998  0.40058638
   0.33623807]
 [-0.30298694 -0.13501456 -0.56166826 ... -0.08960265 -0.7880874
  -0.01142927]
 [-0.1549235   0.37840678  0.0140697  ... -0.2830156   0.62402952
  -0.13313424]]


In [10]:
print(X_train_ft)

[[-5.05265296e-02 -6.77033290e-01 -1.22219689e-01 ... -9.47525829e-01
  -2.76858613e-01 -2.83536866e-01]
 [ 6.39917772e-02  6.66424885e-01 -6.34130223e-01 ...  5.45947965e-01
   9.01945611e-02  7.34044408e-04]
 [-7.39062190e-02  3.22646819e-01 -2.88799298e-01 ... -7.92841963e-02
   2.04668272e-01  4.70877960e-01]
 ...
 [-6.09247546e-03  4.36960966e-01 -1.89189431e-01 ...  9.57665547e-02
   1.13818151e-01  3.89277174e-02]
 [-7.38326250e-01 -2.87758451e-01 -3.72010455e-01 ... -7.98384473e-03
  -7.45760420e-01  4.21409028e-01]
 [-5.54449558e-03  1.53074361e-01 -3.74835118e-01 ...  4.66842860e-02
   5.59791744e-01 -1.22848978e-01]]


#### Test BOW

In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

clf_bow = MultinomialNB()
clf_bow.fit(X_train_bow,y_train_bow)
ypred_bow = clf_bow.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test_bow, ypred_bow))

Accuracy:  0.9410488245931284


In [12]:
from sklearn import tree

clf_bow = tree.DecisionTreeClassifier()
clf_bow.fit(X_train_bow,y_train_bow)
ypred_bow = clf_bow.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test_bow, ypred_bow))

Accuracy:  0.9392405063291139


#### Test TFIDF

In [13]:
clf_tfidf = MultinomialNB()
clf_tfidf.fit(X_train_tfidf,y_train_tfidf)
ypred_tfidf = clf_tfidf.predict(X_test_tfidf)
print("Accuracy: ", accuracy_score(y_test_tfidf, ypred_tfidf))

Accuracy:  0.9482820976491863


In [14]:
clf_tfidf = tree.DecisionTreeClassifier()
clf_tfidf.fit(X_train_tfidf,y_train_tfidf)
ypred_tfidf = clf_tfidf.predict(X_test_tfidf)
print("Accuracy: ", accuracy_score(y_test_tfidf, ypred_tfidf))

Accuracy:  0.941289933694997


#### Test W2V

In [15]:
from sklearn.naive_bayes import GaussianNB

clf_w2v = GaussianNB()
clf_w2v.fit(X_train_w2v,y_train_w2v)
ypred_w2v = clf_w2v.predict(X_test_w2v)
print("Accuracy: ", accuracy_score(y_test_w2v, ypred_w2v))

Accuracy:  0.6988547317661242


In [16]:
from sklearn import tree

clf_w2v = tree.DecisionTreeClassifier().fit(X_train_w2v, y_train_w2v)
clf_w2v.fit(X_train_w2v,y_train_w2v)
ypred_w2v = clf_w2v.predict(X_test_w2v)
print("Accuracy: ", accuracy_score(y_test_w2v, ypred_w2v))

Accuracy:  0.9080168776371308


#### Test FT

In [17]:
clf_ft = GaussianNB()
clf_ft.fit(X_train_ft,y_train_ft)
ypred_ft = clf_ft.predict(X_test_ft)
print("Accuracy: ", accuracy_score(y_test_ft, ypred_ft))

Accuracy:  0.7310427968655817


In [18]:
clf_ft = tree.DecisionTreeClassifier()
clf_ft.fit(X_train_ft,y_train_ft)
ypred_ft = clf_ft.predict(X_test_ft)
print("Accuracy: ", accuracy_score(y_test_ft, ypred_ft))

Accuracy:  0.908499095840868
