In [1]:
import vectorize_functions

In [2]:
X_train_bow, X_test_bow, y_train_bow, y_test_bow = vectorize_functions.vectorize_bow()
X_train_tfidf, X_test_tfidf, y_train_tfidf, y_test_tfidf = vectorize_functions.vectorize_tfidf()
X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = vectorize_functions.vectorize_w2v()
X_train_ft, X_test_ft, y_train_ft, y_test_ft = vectorize_functions.vectorize_ft()

In [3]:
print(X_train_bow.shape)
print(X_test_bow.shape)
print(y_train_bow.shape)
print(y_test_bow.shape)
print(type(X_train_bow))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [4]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)
print(y_train_tfidf.shape)
print(y_test_tfidf.shape)
print(type(X_train_tfidf))

(19354, 6293)
(8295, 6293)
(19354,)
(8295,)
<class 'scipy.sparse._csr.csr_matrix'>


In [5]:
print(X_train_w2v.shape)
print(X_test_w2v.shape)
print(y_train_w2v.shape)
print(y_test_w2v.shape)
print(type(X_train_w2v))

(19354, 300)
(8295, 300)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [6]:
print(X_train_ft.shape)
print(X_test_ft.shape)
print(y_train_ft.shape)
print(y_test_ft.shape)
print(type(X_train_ft))

(19354, 300)
(8295, 300)
(19354,)
(8295,)
<class 'numpy.ndarray'>


In [7]:
print(X_train_bow.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
print(X_train_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
print(X_train_w2v)

[[ 0.56796353 -0.15159982  0.07800473 ...  0.0966844   0.62040487
   0.37300337]
 [-0.46388891  0.28080626 -0.07317242 ...  0.35617909  0.56261509
  -0.07882277]
 [ 0.0529604   0.14233324  0.29700691 ... -0.29135238  0.39866459
  -0.29096323]
 ...
 [-0.18220278 -0.05024931  0.18015918 ... -0.15773222  0.19344942
  -0.08591651]
 [ 0.25784989  0.21942364 -0.06447178 ... -0.00299442  0.17507706
  -0.15309044]
 [-0.15790426 -0.01199974  0.16833096 ... -0.01563819  0.06454587
   0.13174285]]


In [10]:
print(X_train_ft)

[[ 0.31995967 -0.38688827 -0.30881229 ...  0.13753059  0.34691706
  -0.00566745]
 [-1.20015442 -0.36586284 -0.12833088 ...  0.55367259  0.21650805
   1.03176698]
 [-0.05482539  0.25548695  0.02865411 ...  0.10370779 -0.04144042
   0.11050702]
 ...
 [-0.58046529  0.54362163 -0.20929473 ...  0.25916626 -0.22127652
   0.26756146]
 [ 0.71055903 -0.50536022 -0.05073958 ... -0.4339434   0.25084631
   0.07350075]
 [-0.7840914   0.11735571  0.18459035 ...  0.151709   -0.39526167
   0.20821082]]


#### Test BOW

In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

clf_bow = MultinomialNB()
clf_bow.fit(X_train_bow,y_train_bow)
ypred_bow = clf_bow.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test_bow, ypred_bow))

Accuracy:  0.9410488245931284


In [12]:
from sklearn import tree

clf_bow = tree.DecisionTreeClassifier()
clf_bow.fit(X_train_bow,y_train_bow)
ypred_bow = clf_bow.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test_bow, ypred_bow))

Accuracy:  0.937673297166968


#### Test TFIDF

In [13]:
clf_tfidf = MultinomialNB()
clf_tfidf.fit(X_train_tfidf,y_train_tfidf)
ypred_tfidf = clf_tfidf.predict(X_test_tfidf)
print("Accuracy: ", accuracy_score(y_test_tfidf, ypred_tfidf))

Accuracy:  0.9482820976491863


In [14]:
clf_tfidf = tree.DecisionTreeClassifier()
clf_tfidf.fit(X_train_tfidf,y_train_tfidf)
ypred_tfidf = clf_tfidf.predict(X_test_tfidf)
print("Accuracy: ", accuracy_score(y_test_tfidf, ypred_tfidf))

Accuracy:  0.9414104882459313


#### Test W2V

In [15]:
from sklearn.naive_bayes import GaussianNB

clf_w2v = GaussianNB()
clf_w2v.fit(X_train_w2v,y_train_w2v)
ypred_w2v = clf_w2v.predict(X_test_w2v)
print("Accuracy: ", accuracy_score(y_test_w2v, ypred_w2v))

Accuracy:  0.7083785412899337


In [16]:
from sklearn import tree

clf_w2v = tree.DecisionTreeClassifier().fit(X_train_w2v, y_train_w2v)
clf_w2v.fit(X_train_w2v,y_train_w2v)
ypred_w2v = clf_w2v.predict(X_test_w2v)
print("Accuracy: ", accuracy_score(y_test_w2v, ypred_w2v))

Accuracy:  0.9068113321277879


#### Test FT

In [17]:
clf_ft = GaussianNB()
clf_ft.fit(X_train_ft,y_train_ft)
ypred_ft = clf_ft.predict(X_test_ft)
print("Accuracy: ", accuracy_score(y_test_ft, ypred_ft))

Accuracy:  0.7475587703435804


In [18]:
clf_ft = tree.DecisionTreeClassifier()
clf_ft.fit(X_train_ft,y_train_ft)
ypred_ft = clf_ft.predict(X_test_ft)
print("Accuracy: ", accuracy_score(y_test_ft, ypred_ft))

Accuracy:  0.9058468957203134
